### ISSUE TITLE
Shape Mismatch when playing trained model with image observation

### ISSUE THREAD

**Issue by AmanuelErgogo** [ARISE-Initiative/robomimic#110]
### Description
Thanks for this great work!

The issue occurs when trying to play a policy trained using imitation learning in Isaac-orbit. During training, I successfully trained the model with a specific image observation shape of (480, 640, 3), but when I play the model for inference with a frame shape of (480, 640, 3), assertion error (asset frame_input_shape == desired_frame_input_shape) showing a shape mismatch occurs. given that shape of the frame during training and inference is the same.

I have also tried to record and train with different shape of image but it didn't solve.
I wonder how the data is pre-processed when playing the model?
I appreciate your help.

### Error log
```
Traceback (most recent call last):
  File "source/standalone/workflows/robomimic/play.py", line 90, in <module>
    main()
  File "source/standalone/workflows/robomimic/play.py", line 73, in main
    actions = policy(ob=obs)
  File "/home/aman/Orbit/_isaac_sim/kit/python/lib/python3.7/site-packages/robomimic/algo/algo.py", line 518, in __call__
    ac = self.policy.get_action(obs_dict=ob, goal_dict=goal)
  File "/home/aman/Orbit/_isaac_sim/kit/python/lib/python3.7/site-packages/robomimic/algo/bc.py", line 250, in get_action
    return self.nets["policy"](obs_dict, goal_dict=goal_dict)
  File "/home/aman/Orbit/_isaac_sim/kit/python/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/aman/Orbit/_isaac_sim/kit/python/lib/python3.7/site-packages/robomimic/models/policy_nets.py", line 105, in forward
    actions = super(ActorNetwork, self).forward(obs=obs_dict, goal=goal_dict)["action"]
  File "/home/aman/Orbit/_isaac_sim/kit/python/lib/python3.7/site-packages/robomimic/models/obs_nets.py", line 584, in forward
    enc_outputs = self.nets["encoder"](**inputs)
  File "/home/aman/Orbit/_isaac_sim/kit/python/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/aman/Orbit/_isaac_sim/kit/python/lib/python3.7/site-packages/robomimic/models/obs_nets.py", line 445, in forward
    self.nets[obs_group].forward(inputs[obs_group])
  File "/home/aman/Orbit/_isaac_sim/kit/python/lib/python3.7/site-packages/robomimic/models/obs_nets.py", line 235, in forward
    x = self.obs_nets[k](x)
  File "/home/aman/Orbit/_isaac_sim/kit/python/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/aman/Orbit/_isaac_sim/kit/python/lib/python3.7/site-packages/robomimic/models/obs_core.py", line 172, in forward
    assert tuple(inputs.shape)[-ndim:] == tuple(self.input_shape)
AssertionError
```

**Comment by amandlek** [comment]
Thanks for bringing this issue up. I am not too familiar with how Orbit interfaces with robomimic, so I would suggest posting an issue on their repo as well. However, my best guess is that this is related to image preprocessing operations that should take place when images are loaded from the dataset / from the simulation environment (operations such as changing from uint8 to float, and re-ordering the batch to be channel-first, e.g. B-C-H-W, instead of B-H-W-C - see [here](https://github.com/ARISE-Initiative/robomimic/blob/43d17472e64333f62c457199531a11de5a47b370/robomimic/utils/obs_utils.py#L365))
