### ISSUE TITLE
error when set rollout.enable=True

### ISSUE THREAD

**Issue by kavinwkp** [ARISE-Initiative/robomimic#113]
```
Exception ignored in: <function MjRenderContext.__del__ at 0x7f0f9c1ca940>
Traceback (most recent call last):
  File "/home/kavin/Documents/GitProjects/RL/robosuite/robosuite/utils/binding_utils.py", line 199, in __del__
    self.gl_ctx.free()
  File "/home/kavin/Documents/GitProjects/RL/robosuite/robosuite/renderers/context/egl_context.py", line 149, in free
    EGL.eglMakeCurrent(EGL_DISPLAY, EGL.EGL_NO_SURFACE, EGL.EGL_NO_SURFACE, EGL.EGL_NO_CONTEXT)
  File "/home/kavin/anaconda3/envs/mimicgen/lib/python3.8/site-packages/OpenGL/error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.raw.EGL._errors.EGLError: EGLError(
	err = EGL_NOT_INITIALIZED,
	baseOperation = eglMakeCurrent,
	cArguments = (
		<OpenGL._opaque.EGLDisplay_pointer object at 0x7f0f871c0a40>,
		<OpenGL._opaque.EGLSurface_pointer object at 0x7f0f9c24c2c0>,
		<OpenGL._opaque.EGLSurface_pointer object at 0x7f0f9c24c2c0>,
		<OpenGL._opaque.EGLContext_pointer object at 0x7f0f9c2e2c40>,
	),
	result = 0
)
```
Can you tell me how to fix it or it can be ignored?

**Comment by amandlek** [comment]
This issue can be ignored. See https://github.com/ARISE-Initiative/robomimic/issues/56
