### ISSUE TITLE
How do I fix it?

### ISSUE THREAD

**Issue by SshiJwu** [ARISE-Initiative/robomimic#136]
when I run "examples/train_bc_rnn.py --bebug", something went wrong.

Epoch 2 Memory Usage: 1030 MB

Exception ignored in: <function MjRenderContext.__del__ at 0x7fa1b109e310>
Traceback (most recent call last):
  File "/home/user/Downloads/robosuite-master/robosuite/utils/binding_utils.py", line 199, in __del__
    self.gl_ctx.free()
  File "/home/user/Downloads/robosuite-master/robosuite/renderers/context/egl_context.py", line 149, in free
    EGL.eglMakeCurrent(EGL_DISPLAY, EGL.EGL_NO_SURFACE, EGL.EGL_NO_SURFACE, EGL.EGL_NO_CONTEXT)
  File "/home/user/miniconda3/envs/robomimic_venv/lib/python3.8/site-packages/OpenGL/error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.raw.EGL._errors.EGLError: EGLError(
        err = EGL_NOT_INITIALIZED,
        baseOperation = eglMakeCurrent,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7fa1a6735ec0>,
                <OpenGL._opaque.EGLSurface_pointer object at 0x7fa1c9044a40>,
                <OpenGL._opaque.EGLSurface_pointer object at 0x7fa1c9044a40>,
                <OpenGL._opaque.EGLContext_pointer object at 0x7fa1c9044cc0>,
        ),
        result = 0
)
Exception ignored in: <function EGLGLContext.__del__ at 0x7fa1b109e160>
Traceback (most recent call last):
  File "/home/user/Downloads/robosuite-master/robosuite/renderers/context/egl_context.py", line 155, in __del__
    self.free()
  File "/home/user/Downloads/robosuite-master/robosuite/renderers/context/egl_context.py", line 149, in free
    EGL.eglMakeCurrent(EGL_DISPLAY, EGL.EGL_NO_SURFACE, EGL.EGL_NO_SURFACE, EGL.EGL_NO_CONTEXT)
  File "/home/user/miniconda3/envs/robomimic_venv/lib/python3.8/site-packages/OpenGL/error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.raw.EGL._errors.EGLError: EGLError(
        err = EGL_NOT_INITIALIZED,
        baseOperation = eglMakeCurrent,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7fa1a6735ec0>,
                <OpenGL._opaque.EGLSurface_pointer object at 0x7fa1c9044a40>,
                <OpenGL._opaque.EGLSurface_pointer object at 0x7fa1c9044a40>,
                <OpenGL._opaque.EGLContext_pointer object at 0x7fa1c9044cc0>,
        ),
        result = 0
)

**Comment by amandlek** [comment]
This seems like an issue with EGL rendering with your mujoco / robosuite installation. Have you verified that offscreen rendering works for you with robosuite environments? For example, you could try this script [here](https://github.com/ARISE-Initiative/robosuite/blob/48c1b8a6c077d04399a00db05694d7f9f876ffc9/robosuite/scripts/make_reset_video.py). It may also be worth posting the issue there, as this is not a robomimic issue.
