### ISSUE TITLE
AttributeError: 'SequenceDataset' object has no attribute '_hdf5_file'

### ISSUE THREAD

**Issue by TousakaNagio** [ARISE-Initiative/robomimic#201]
Exception ignored in: <function SequenceDataset.__del__ at 0x7f6ed46b2a70>
Traceback (most recent call last):
  File "/home/shinji106/ntu/robocasa/robomimic/robomimic/utils/dataset.py", line 307, in __del__
    self.close_and_delete_hdf5_handle()
  File "/home/shinji106/ntu/robocasa/robomimic/robomimic/utils/dataset.py", line 291, in close_and_delete_hdf5_handle
    if self._hdf5_file is not None:
AttributeError: 'SequenceDataset' object has no attribute '_hdf5_file'
run failed with error:
expected str, bytes or os.PathLike object, not list

Traceback (most recent call last):
  File "/home/shinji106/ntu/robocasa/robomimic/robomimic/scripts/train.py", line 483, in main
    train(config, device=device, eval_only=args.eval_only)
  File "/home/shinji106/ntu/robocasa/robomimic/robomimic/scripts/train.py", line 187, in train
    trainset, validset = TrainUtils.load_data_for_training(
  File "/home/shinji106/ntu/robocasa/robomimic/robomimic/utils/train_utils.py", line 137, in load_data_for_training
    train_dataset = dataset_factory(
  File "/home/shinji106/ntu/robocasa/robomimic/robomimic/utils/train_utils.py", line 197, in dataset_factory
    dataset = get_dataset(
  File "/home/shinji106/ntu/robocasa/robomimic/robomimic/utils/train_utils.py", line 231, in get_dataset
    ds_list.append(ds_class(**ds_kwargs_copy))
  File "/home/shinji106/ntu/robocasa/robomimic/robomimic/utils/dataset.py", line 105, in __init__
    self.hdf5_path = os.path.expanduser(hdf5_path)
  File "/home/shinji106/miniconda3/envs/robocasa/lib/python3.10/posixpath.py", line 232, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not list

I run into several issues when I am trying to run the training script of bc_transformer on robocasa. How can I solve these issues?

**Comment by TousakaNagio** [comment]
The title error occurs due to the error of TypeError: expected str, bytes or os.PathLike object, not list.
I am still wondering why the generated training config contains a list of path to the dataset:

"train": {
        "data": [
            {
                "path": [
                    "/data/robocasa/v0.1/multi_stage/brewing/PrepareCoffee/2024-05-07/demo_im128.hdf5",
                    null
                ],
                "horizon": 1000,
                "do_eval": true,
                "filter_key": "50_demos"
            }
        ],
        "output_dir": "/home/shinji106/ntu/robocasa/robomimic/expdata/robocasa/bc_xfmr/10-22-bc_test_1022",
        "num_data_workers": 5,
        "hdf5_cache_mode": null,
        "hdf5_use_swmr": true,
        "hdf5_load_next_obs": false,
        "hdf5_normalize_obs": false,
        "hdf5_filter_key": null,
        "seq_length": 10,
        "pad_seq_length": true,
        "frame_stack": 10,
        "pad_frame_stack": true,
        "dataset_keys": [
            "actions"
        ],
        "goal_mode": null,
        "cuda": true,
        "batch_size": 16,
        "num_epochs": 1000,
        "max_grad_norm": 100.0,
        "seed": 123,
        "action_config": {
            "actions": {
                "normalization": null
            },
            "actions_abs": {
                "normalization": "min_max"
            },
            "action_dict/abs_pos": {
                "normalization": "min_max"
            },
            "action_dict/abs_rot_axis_angle": {
                "normalization": "min_max",
                "format": "rot_axis_angle"
            },
            "action_dict/abs_rot_6d": {
                "normalization": null,
                "format": "rot_6d"
            },
            "action_dict/rel_pos": {
                "normalization": null
            },
            "action_dict/rel_rot_axis_angle": {
                "normalization": null,
                "format": "rot_axis_angle"
            },
            "action_dict/rel_rot_6d": {
                "normalization": null,
                "format": "rot_6d"
            },
            "action_dict/gripper": {
                "normalization": null
            },
            "action_dict/base_mode": {
                "normalization": null
            }
        }
    }

I am wondering why the generated config contains a list of paths.
If I replace it with a path, the second error occurs:

Traceback (most recent call last):
  File "/home/shinji106/ntu/robocasa/robomimic/robomimic/scripts/train.py", line 482, in main
    train(config, device=device, eval_only=args.eval_only)
  File "/home/shinji106/ntu/robocasa/robomimic/robomimic/scripts/train.py", line 186, in train
    trainset, validset = TrainUtils.load_data_for_training(
  File "/home/shinji106/ntu/robocasa/robomimic/robomimic/utils/train_utils.py", line 137, in load_data_for_training
    train_dataset = dataset_factory(
  File "/home/shinji106/ntu/robocasa/robomimic/robomimic/utils/train_utils.py", line 197, in dataset_factory
    dataset = get_dataset(
  File "/home/shinji106/ntu/robocasa/robomimic/robomimic/utils/train_utils.py", line 231, in get_dataset
    ds_list.append(ds_class(**ds_kwargs_copy))
  File "/home/shinji106/ntu/robocasa/robomimic/robomimic/utils/dataset.py", line 145, in __init__
    self.load_demo_info(filter_by_attribute=self.filter_by_attribute)
  File "/home/shinji106/ntu/robocasa/robomimic/robomimic/utils/dataset.py", line 207, in load_demo_info
    self.demos = [elem.decode("utf-8") for elem in np.array(self.hdf5_file["mask/{}".format(filter_by_attribute)][:])]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/shinji106/miniconda3/envs/robocasa/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 804, in __getitem__
    mtype = h5t.py_create(new_dtype)
  File "h5py/h5t.pyx", line 1669, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1693, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1731, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1544, in h5py.h5t._c_string
ValueError: Size must be positive (size must be positive)
