### ISSUE TITLE
KeyError: 'Unable to open object (component not found)'

### ISSUE THREAD

**Issue by nuomizai** [ARISE-Initiative/robomimic#48]
When I tried to train a cql agent with the following command:
```
python robomimic/scripts/train.py --dataset datasets/can/mg/low_dim_sparse.hdf5 --config robomimic/exps/templates/cql.json 
```
An error occurs:
```
run failed with error:
'Unable to open object (component not found)'

Traceback (most recent call last):
  File "robomimic/scripts/train.py", line 355, in main
    train(config, device=device)
  File "robomimic/scripts/train.py", line 132, in train
    config, obs_keys=shape_meta["all_obs_keys"])
  File "/home/quan/robomimic/robomimic/utils/train_utils.py", line 106, in load_data_for_training
    train_dataset = dataset_factory(config, obs_keys, filter_by_attribute=train_filter_by_attribute)
  File "/home/quan/robomimic/robomimic/utils/train_utils.py", line 153, in dataset_factory
    dataset = SequenceDataset(**ds_kwargs)
  File "/home/quan/robomimic/robomimic/utils/dataset.py", line 116, in __init__
    self.load_demo_info(filter_by_attribute=self.filter_by_attribute)
  File "/home/quan/robomimic/robomimic/utils/dataset.py", line 170, in load_demo_info
    self.demos = [elem.decode("utf-8") for elem in np.array(self.hdf5_file["mask/{}".format(filter_by_attribute)][:])]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/quan/anaconda3/envs/hand/lib/python3.7/site-packages/h5py/_hl/group.py", line 305, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (component not found)'

```

But when I train a cql agent in a human-generated dataset, everything works fine with the following command 
```
python robomimic/scripts/train.py --dataset datasets/can/mh/low_dim.hdf5 --config robomimic/exps/templates/cql.json
```

Does anyone know what's wrong with it?

**Comment by amandlek** [comment]
This is because the default training config tries to use a validation data subset, but the machine-generated data doesn't have a validation subset. I recommend using the instructions [here](https://robomimic.github.io/docs/datasets/robomimic_v0.1.html#reproduce-study-results) to generate configs that correspond to our experiments on the machine-generated datasets. Alternatively, you can create a train-valid split in that dataset if you'd like - see [here](https://robomimic.github.io/docs/datasets/overview.html#filter-keys) for more information. Hope that helps!
