### ISSUE TITLE
Issue with get_observation function of robomimic env

### ISSUE THREAD

**Issue by StoneT2000** [ARISE-Initiative/robomimic#96]
I currently am running the following

```
import robomimic.utils.file_utils as FileUtils
    import robomimic.utils.env_utils as EnvUtils
    from matplotlib import pyplot as plt

    dataset_path = "demos/robomimic/tool_hang/ph/low_dim_v141.hdf5"
    env_meta = FileUtils.get_env_metadata_from_dataset(
        dataset_path)

    env = EnvUtils.create_env_from_metadata(
        env_meta=env_meta,
        render=False, 
        render_offscreen=False,
        use_image_obs=False, 
    )
```

But running `env.get_observation()` reports an error
```
Created environment with name ToolHang
Action size is 7
Traceback (most recent call last):
  File "/home/stao/work/research/rfcl-temp/test.py", line 138, in <module>
    test()
  File "/home/stao/work/research/rfcl-temp/test.py", line 113, in test
    env.get_observation()
  File "/home/stao/work/external/robomimic/robomimic/envs/env_robosuite.py", line 200, in get_observation
    if (k in ObsUtils.OBS_KEYS_TO_MODALITIES) and ObsUtils.key_is_obs_modality(key=k, obs_modality="rgb"):
TypeError: argument of type 'NoneType' is not iterable
```
Any idea?

**Comment by amandlek** [comment]
Yes, you need to initialize `ObsUtils` using a code pattern such as [this one](https://github.com/ARISE-Initiative/robomimic/blob/e816587beb6a90c1a9d7977191913a90a216c923/robomimic/scripts/playback_dataset.py#L210). This is necessary to ensure observations are postprocessed appropriately (for example for use with the kwarg [here](https://github.com/ARISE-Initiative/robomimic/blob/e816587beb6a90c1a9d7977191913a90a216c923/robomimic/envs/env_robosuite.py#L53)).
